// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdA0UdUt2XF65SZbBS3uvO7cXX03Adzrk',
    appId: '1:805740518939:web:e9f5d19181c737bfaba2be',
    messagingSenderId: '805740518939',
    projectId: 'yourspot-3cd1b',
    authDomain: 'yourspot-3cd1b.firebaseapp.com',
    storageBucket: 'yourspot-3cd1b.appspot.com',
    measurementId: 'G-1K1WCD3JK3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYT06AfNfkCkbFkFtrHhpZxRWFN2ps3xI',
    appId: '1:805740518939:android:eb8aac4465311dc2aba2be',
    messagingSenderId: '805740518939',
    projectId: 'yourspot-3cd1b',
    storageBucket: 'yourspot-3cd1b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAFoIUZaxvThxS-oojbLKV_bcv_anmSHs',
    appId: '1:808217278836:ios:f7d539b2068ed648285421',
    messagingSenderId: '808217278836',
    projectId: 'finalsmartparking',
    storageBucket: 'finalsmartparking.appspot.com',
    iosClientId:
        '808217278836-amc3smocp7qpl6pq7f8vs9pol7dk1jkb.apps.googleusercontent.com',
    iosBundleId: 'com.example.yourspotApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCy3D0CYJwEeyxjl3t4rWoDAo0vW5D78N0',
    appId: '1:805740518939:ios:f7ef4a48aa91a570aba2be',
    messagingSenderId: '805740518939',
    projectId: 'yourspot-3cd1b',
    storageBucket: 'yourspot-3cd1b.appspot.com',
    iosClientId:
        '805740518939-h4gm2p2osbpi7o74rpji6349f5qb02j0.apps.googleusercontent.com',
    iosBundleId: 'com.example.yourspotApp.RunnerTests',
  );
}
