// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDI0_VAAZ3gnlUD3cHIwekbRQ_tHsNdg0Q',
    appId: '1:808217278836:android:8d3b4e994f7fcd37285421',
    messagingSenderId: '808217278836',
    projectId: 'finalsmartparking',
    databaseURL: 'https://finalsmartparking-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'finalsmartparking.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAFoIUZaxvThxS-oojbLKV_bcv_anmSHs',
    appId: '1:808217278836:ios:f7d539b2068ed648285421',
    messagingSenderId: '808217278836',
    projectId: 'finalsmartparking',
    databaseURL: 'https://finalsmartparking-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'finalsmartparking.appspot.com',
    iosClientId: '808217278836-amc3smocp7qpl6pq7f8vs9pol7dk1jkb.apps.googleusercontent.com',
    iosBundleId: 'com.example.yourspotApp',
  );
}
